export const clientScript = String.raw`
(() => {
'use strict';
const content = document.getElementById('content');
const notice = document.getElementById('notice');
let session = null, authEnabled = false, noticeTimer, renderVersion = 0, providerSessionId = null;
const escape = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = value => new Date(value).toLocaleDateString('en-ZA',{day:'numeric',month:'short',year:'numeric'});
const pathId = value => encodeURIComponent(value);
const pill = value => '<span class="pill '+(value==='Rejected'||value==='Withdrawn'||value==='CLOSED'?'gray':'blue')+'">'+escape(value)+'</span>';
const empty = (title,description) => '<div class="empty"><h3>'+escape(title)+'</h3><p>'+escape(description)+'</p></div>';
const button = (action,label,id='',extra='') => '<button class="button small '+extra+'" data-action="'+action+'" data-id="'+escape(id)+'">'+escape(label)+'</button>';
function flash(message){notice.textContent=message;notice.hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>notice.hidden=true,6500);}
const messages={UNAUTHENTICATED:'Please sign in to continue.',FORBIDDEN:'Your account does not have access to this workspace.',ACTIVE_APPLICATION_EXISTS:'You already have an active application for this opportunity.',CANDIDATE_SKILL_EXISTS:'That skill is already on your profile.',VACANCY_REQUIREMENT_EXISTS:'That requirement is already listed.',VACANCY_NOT_OPEN:'This opportunity is no longer accepting applications.',INVALID_APPLICATION_TRANSITION:'This application has changed. Refresh and check its current status.',INVALID_VACANCY_TRANSITION:'This vacancy has changed. Refresh and check its current status.',ACCOUNT_REQUIRES_SUPPORT:'An account already uses this email. Contact HiredFlex to connect it safely.',VERIFIED_EMAIL_REQUIRED:'Verify your primary email address in your account before continuing.',IDENTITY_UNAVAILABLE:'Sign-in is temporarily unavailable. Please try again.',INVALID_VACANCY_REQUIREMENT_STATE:'Requirements can only be edited while a vacancy is in draft.',NOT_FOUND:'This record is no longer available.'};
async function api(url,method='GET',body){
 const headers={};const token=await window.Clerk?.session?.getToken();if(token)headers.Authorization='Bearer '+token;
 if(body!==undefined)headers['Content-Type']='application/json';
 const res=await fetch(url,{method,headers,body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});
 if(res.status===204)return null;const data=await res.json();
 if(!res.ok){const error=new Error(messages[data.error?.code]||'Unable to complete this request. Please try again.');error.code=data.error?.code;throw error;}return data;
}
async function refreshSession(){
 session=null;
 if(window.Clerk?.session){try{session=await api('/auth/session');}catch(error){if(error.code!=='UNAUTHENTICATED')throw error;}}
 document.getElementById('sign-in').hidden=Boolean(window.Clerk?.session);
 document.getElementById('sign-out').hidden=!window.Clerk?.session;
}
function role(name){return session?.roleAssignments.some(item=>item.role===name);}
function tabs(active){return '<div class="tabs">'+(role('Candidate')?'<a class="'+(active==='overview'?'active':'')+'" href="#workspace">Overview</a><a class="'+(active==='skills'?'active':'')+'" href="#skills">My skills</a><a class="'+(active==='applications'?'active':'')+'" href="#applications">Applications</a>':'')+(role('Employer')?'<a class="'+(active==='employer'?'active':'')+'" href="#employer">Employer</a>':'')+(role('Recruiter')?'<a class="'+(active==='recruiter'?'active':'')+'" href="#recruiter">Recruiter</a>':'')+'</div>';}
function heading(kicker,title,description=''){return '<div class="section-heading"><div><span class="eyebrow">'+escape(kicker)+'</span><h2>'+escape(title)+'</h2><p>'+escape(description)+'</p></div></div>';}
function home(){return '<section class="hero"><div><span class="eyebrow">Your next chapter starts here</span><h1>Great talent.<br>Real opportunities.<br><span class="accent">One connection.</span></h1><p>Build your skills profile, explore open roles and follow every application — all in one place.</p><div class="actions"><a class="button" href="#jobs">Explore opportunities <span aria-hidden="true">↗</span></a><a class="button quiet" href="#workspace">Open my workspace</a></div><small>Designed for job seekers. Built around people.</small></div><div class="hero-art" aria-label="Illustration of matching and application tracking"><div class="sample-card"><span class="sample-label">A clearer picture of your skills</span><div class="sample-top"><span class="tile">✓</span><div><h3>Your skills, explained</h3><small>See matched and missing requirements</small></div></div><div class="bar"><span></span></div><span class="pill blue">Transparent matching</span></div><div class="sample-card offset"><span class="sample-label">Every step, in one place</span><h3>Keep your next move in sight.</h3><span class="pill">Applied</span> <span class="pill gray">Reviewing</span></div></div></section><section class="feature-grid"><div class="feature"><span class="number">01 / DISCOVER</span><h3>Find your direction.</h3><p>Browse open opportunities by title and location.</p></div><div class="feature"><span class="number">02 / UNDERSTAND</span><h3>Know where you match.</h3><p>Compare your skills with listed requirements, with a clear explanation.</p></div><div class="feature"><span class="number">03 / MOVE FORWARD</span><h3>Track your progress.</h3><p>Apply, follow status updates and manage your next steps.</p></div></section>';}
function jobCard(item){const id=item.vacancyId||item.id;return '<article class="card"><span class="pill blue">Open opportunity</span><h3>'+escape(item.title)+'</h3><p class="meta">'+escape(item.location||'Location not specified')+'</p>'+(Object.hasOwn(item,'percentage')?'<p>'+escape(item.summary)+'</p>':'<p>'+escape((item.description||'View this opportunity for more details.').slice(0,150))+'</p>')+'<a class="button quiet small" href="#job/'+pathId(id)+'">View opportunity ↗</a></article>';}
async function jobs(query){const search=new URLSearchParams(query||'');const q=search.get('q')||'',location=search.get('location')||'';const filters=new URLSearchParams();if(q.trim())filters.set('q',q.trim());if(location.trim())filters.set('location',location.trim());const items=await api('/vacancies?'+filters);return heading('Find your next move','Open opportunities','Explore roles currently accepting applications.')+'<form class="filters" data-form="search"><label>Role or keyword<input name="q" maxlength="200" value="'+escape(q)+'" placeholder="e.g. Technical Support"></label><label>Location<input name="location" maxlength="200" value="'+escape(location)+'" placeholder="e.g. Johannesburg"></label><button class="button" type="submit">Search opportunities</button></form><div class="grid">'+(items.length?items.map(jobCard).join(''):empty('No opportunities found','Try another keyword or location. New roles will appear here when employers publish them.'))+'</div>';}
async function job(id){const vacancy=await api('/vacancies/'+pathId(id));let match='';if(role('Candidate')){const result=await api('/candidate/vacancies/'+pathId(id)+'/match');match='<div class="card"><span class="eyebrow">Your match overview</span><p class="score">'+(result.percentage===null?'—':escape(result.percentage)+'%')+'</p><p>'+escape(result.summary)+'</p><small>Informational only. This is not a prediction of hiring success.</small>';for(const [key,label] of [['matched','Matched requirements'],['missing','Missing requirements'],['notEvaluated','Not evaluated']]){const rows=result[key+'Requirements']||[];match+='<h3>'+label+'</h3><ul class="explanation">'+(rows.length?rows.map(row=>'<li>'+escape(row.name||row.requirementId)+'</li>').join(''):'<li>None</li>')+'</ul>';}match+='</div>';}
return '<a class="back" href="#jobs">← All opportunities</a>'+heading('Open opportunity',vacancy.title,vacancy.location||'Location not specified')+'<div class="split"><div class="card"><h3>About this opportunity</h3><p class="detail-text">'+escape(vacancy.description||'No additional description has been provided.')+'</p><div class="actions">'+(role('Candidate')?button('apply','Apply for this role',id):'<a class="button" href="#workspace">Sign in to apply</a>')+'</div></div><aside>'+match+'</aside></div>';}
async function workspace(){if(!window.Clerk?.session)return signIn();if(!session)return heading('Welcome to HiredFlex','Finish setting up your profile','Your candidate account will let you manage skills, apply for roles and track progress.')+'<div class="card compact"><h3>Ready for your next chapter?</h3><p>HiredFlex will store your verified email, name, skills and application activity. You can read how your data is used below.</p><p><a class="back" href="#privacy">Privacy &amp; data</a></p>'+button('onboard','Create my candidate profile')+'</div>';const result=role('Candidate')?await api('/candidate/vacancy-matches?limit=6'):null;return heading('Your workspace','Welcome, '+session.displayName,'Make your next move with confidence.')+tabs('overview')+(role('Candidate')?'<div class="actions"><a class="button" href="#skills">Manage my skills</a><a class="button quiet" href="#applications">Track applications</a></div><h3>Opportunities matched to your skills</h3><p class="muted">Ranked by the percentage of evaluable listed requirements matched.</p><div class="grid">'+(result.items.length?result.items.map(jobCard).join(''):empty('Your next opportunity is on its way','Add your skills now. Open opportunities will appear here when they are published.'))+'</div>':'<p>Choose your workspace above.</p>');}
async function skills(){const items=await api('/candidate/skills');return heading('Your candidate profile','Skills that tell your story','Add specific skills. Matching uses normalized exact skill names.')+tabs('skills')+'<div class="split"><div class="card"><h3>My skills</h3><div class="chips">'+(items.length?items.map(item=>'<span class="chip">'+escape(item.skillName)+'<button data-action="remove-skill" data-id="'+escape(item.id)+'" aria-label="Remove '+escape(item.skillName)+'">×</button></span>').join(''):'<p>No skills yet. Add your first skill to get started.</p>')+'</div></div><form class="card" data-form="skill"><label>Skill name<input name="skillName" required maxlength="200" placeholder="e.g. JavaScript"></label><button class="button" type="submit">Add skill</button></form></div>';}
async function applications(){const items=await api('/candidate/applications');return heading('Keep moving forward','My applications','Follow your application status and review its history.')+tabs('applications')+'<div class="card">'+(items.length?items.map(item=>'<div class="row"><div><a href="#application/'+pathId(item.id)+'"><h3>'+escape(item.vacancyTitle)+'</h3></a><small>Applied '+date(item.submittedAt)+'</small></div><div>'+pill(item.currentStatus)+' <a class="button quiet small" href="#application/'+pathId(item.id)+'">View history</a></div></div>').join(''):empty('No applications yet','Explore opportunities and apply when you find the right fit.'))+'</div>';}
async function application(id){const item=await api('/candidate/applications/'+pathId(id));return '<a class="back" href="#applications">← My applications</a>'+heading('Application details',item.vacancyTitle)+pill(item.currentStatus)+'<div class="split"><div class="card"><h3>Status history</h3>'+item.history.map(row=>'<div class="row"><span>'+escape(row.toStatus)+'</span><small>'+date(row.occurredAt)+'</small></div>').join('')+'</div><aside class="card"><h3>Your application</h3><p>Submitted '+date(item.submittedAt)+'</p>'+(['Applied','Reviewing','Shortlisted'].includes(item.currentStatus)?button('withdraw','Withdraw application',id,'danger'):'<p>This application is closed.</p>')+'</aside></div>';}
async function employer(){const [items,companies]=await Promise.all([api('/employer/vacancies'),api('/employer/companies')]);return heading('Employer workspace','Build your next great team','Create a draft, define requirements, then publish your opportunity.')+tabs('employer')+'<div class="split"><div class="stack">'+(items.length?items.map(item=>'<article class="card">'+pill(item.status)+'<h3>'+escape(item.title)+'</h3><p>'+escape(item.location||'Location not specified')+'</p><a class="button quiet small" href="#manage/'+pathId(item.id)+'">Manage vacancy</a></article>').join(''):empty('No vacancies yet','Create your first draft using the form.'))+'</div><form class="card" data-form="vacancy"><h3>Create a vacancy</h3><label>Company<select name="companyId" required>'+companies.map(item=>'<option value="'+escape(item.id)+'">'+escape(item.name)+'</option>').join('')+'</select></label><label>Role title<input name="title" required maxlength="240"></label><label>Location<input name="location" maxlength="500"></label><label>Role description<textarea name="description" maxlength="20000"></textarea></label><button class="button" type="submit">Create draft</button></form></div>';}
function applicantRows(items,review=false){return items.length?items.map(item=>'<div class="row"><div><h3>Candidate '+escape(item.candidateId.slice(0,8))+'</h3><small>Applied '+date(item.submittedAt)+'</small></div><div>'+pill(item.currentStatus)+(review&&['Applied','Reviewing'].includes(item.currentStatus)?'<div class="actions">'+(item.currentStatus==='Applied'?button('review','Review',item.id):'')+button('shortlist','Shortlist',item.id)+button('reject','Reject',item.id,'danger')+'</div>':'')+'</div></div>').join(''):empty('No applications yet','Applications will appear here once candidates apply.');}
async function manage(id){const [vacancy,requirements,items,people]=await Promise.all([api('/employer/vacancies/'+pathId(id)),api('/employer/vacancies/'+pathId(id)+'/requirements'),api('/employer/vacancies/'+pathId(id)+'/applications'),api('/employer/recruiters')]);return '<a class="back" href="#employer">← My vacancies</a>'+heading('Manage opportunity',vacancy.title,vacancy.location||'')+pill(vacancy.status)+'<div class="actions">'+(vacancy.status==='DRAFT'?button('open-vacancy','Publish opportunity',id):vacancy.status==='OPEN'?button('close-vacancy','Close opportunity',id,'danger'):'')+'</div><div class="split"><div class="stack"><section class="card"><h3>Listed requirements</h3>'+requirements.map(item=>'<div class="row"><div><strong>'+escape(item.skillName||item.description)+'</strong><p>'+escape(item.description)+'</p><small>'+(item.required?'Required':'Preferred')+'</small></div>'+(vacancy.status==='DRAFT'?'<button class="button quiet small" data-action="remove-requirement" data-id="'+escape(item.id)+'" data-vacancy="'+escape(id)+'">Remove</button>':'')+'</div>').join('')+(!requirements.length?'<p>No requirements added yet.</p>':'')+'</section><section class="card"><h3>Applications</h3>'+applicantRows(items)+'</section></div><aside class="stack">'+(vacancy.status==='DRAFT'?'<form class="card" data-form="requirement" data-id="'+escape(id)+'"><h3>Add a skill requirement</h3><label>Skill name<input name="skillName" required maxlength="200"></label><label>Description<input name="description" required maxlength="1000"></label><label>Importance<select name="required"><option value="true">Required</option><option value="false">Preferred</option></select></label><button class="button" type="submit">Add requirement</button></form>':'<div class="card"><p>Requirements are locked after publishing.</p></div>')+'<form class="card" data-form="assign" data-id="'+escape(id)+'"><h3>Assigned recruiter</h3><label>Recruiter<select name="recruiterId" required><option value="">Choose recruiter</option>'+people.filter(person=>person.companyId===null||person.companyId===vacancy.companyId).map(person=>'<option value="'+escape(person.id)+'" '+(person.id===vacancy.assignedRecruiterId?'selected':'')+'>'+escape(person.displayName)+'</option>').join('')+'</select></label><button class="button quiet" type="submit">Assign recruiter</button><p>Only assigned recruiters can review and decide applications.</p></form></aside></div>';}
async function recruiter(){const items=await api('/recruiter/vacancies');return heading('Recruiter workspace','Your assigned opportunities','Review applications for the vacancies assigned to you.')+tabs('recruiter')+'<div class="grid">'+(items.length?items.map(item=>'<article class="card">'+pill(item.status)+'<h3>'+escape(item.title)+'</h3><p>'+escape(item.location||'')+'</p><a class="button quiet small" href="#review/'+pathId(item.id)+'">Review applications</a></article>').join(''):empty('No assigned vacancies','An employer must assign you to a vacancy before you can review its applications.'))+'</div>';}
async function review(id){const items=await api('/recruiter/vacancies/'+pathId(id)+'/applications');return '<a class="back" href="#recruiter">← Assigned opportunities</a>'+heading('Recruitment pipeline','Review applications','Application decisions are recorded in the status history.')+'<section class="card">'+applicantRows(items,true)+'</section>';}
function privacy(){return '<article class="privacy">'+heading('Your information','Privacy & data','How this first release uses your information.')+'<h3>Information used</h3><p>HiredFlex stores your verified email address, display name, the skills you add and your application history. The sign-in provider manages login verification and account security.</p><h3>Who can see applications</h3><p>Applications are available to you, authorised members of the vacancy’s company and the recruiter assigned to the vacancy. Public opportunity listings do not expose your account details.</p><h3>Matching explanations</h3><p>Matching compares normalized exact skill names against structured requirements. It does not infer experience, judge your suitability or make a hiring decision. Descriptive requirements without a structured skill are shown as not evaluated.</p><h3>Your choices</h3><p>You can remove skills and withdraw active applications in your workspace. Application history remains for recruitment accountability. For account or data requests, contact the HiredFlex representative who invited you to the platform.</p><h3>Before sharing documents</h3><p>This release does not accept CV uploads. Do not add identity numbers, financial information or sensitive personal information as skills or application text.</p></article>';}
function signIn(){if(!authEnabled)return heading('Welcome to HiredFlex','Sign-in is being prepared','You can browse published opportunities while account access is being configured.');return heading('Your next chapter','Sign in to your workspace','Create an account or sign in to continue.')+'<div class="card compact"><p>Secure sign-in keeps your profile and applications connected to you.</p>'+button('begin-signin','Sign in or create an account')+'</div>';}
async function render(){const version=++renderVersion;const raw=location.hash.slice(1)||'home';const [route,query]=raw.split('?');const [page,id]=route.split('/');content.innerHTML='<p class="loading">Loading…</p>';try{let html;if(page==='home')html=home();else if(page==='jobs')html=await jobs(query);else if(page==='job'&&id)html=await job(id);else if(page==='privacy')html=privacy();else if(page==='workspace')html=await workspace();else if(!session)html=await workspace();else if(page==='skills')html=await skills();else if(page==='applications')html=await applications();else if(page==='application'&&id)html=await application(id);else if(page==='employer')html=await employer();else if(page==='manage'&&id)html=await manage(id);else if(page==='recruiter')html=await recruiter();else if(page==='review'&&id)html=await review(id);else html=home();if(version===renderVersion){content.innerHTML=html;document.getElementById('main').focus({preventScroll:true});}}catch(error){if(version===renderVersion)content.innerHTML=empty('We couldn’t load this page',error.message)+'<div class="actions">'+button('retry','Try again')+'<a class="button quiet" href="#home">Go home</a></div>';}}
async function action(event){const target=event.target.closest('[data-action]');if(!target)return;const {action,id,vacancy}=target.dataset;target.disabled=true;try{if(action==='begin-signin'){window.Clerk.openSignIn({forceRedirectUrl:window.location.origin+'/#workspace',signUpForceRedirectUrl:window.location.origin+'/#workspace'});return;}if(action==='retry'){await render();return;}if(action==='onboard'){await api('/auth/onboard','POST',{});await refreshSession();flash('Your candidate profile is ready.');}if(action==='apply'){await api('/candidate/applications','POST',{vacancyId:id});flash('Application submitted.');location.hash='applications';return;}if(action==='remove-skill'){await api('/candidate/skills/'+pathId(id),'DELETE');flash('Skill removed.');}if(action==='withdraw'){if(!confirm('Withdraw this application? Its status history will be kept.'))return;await api('/candidate/applications/'+pathId(id)+'/withdraw','POST');flash('Application withdrawn.');}if(action==='remove-requirement'){await api('/employer/vacancies/'+pathId(vacancy)+'/requirements/'+pathId(id),'DELETE');flash('Requirement removed.');}if(action==='open-vacancy'||action==='close-vacancy'){if(!confirm(action==='open-vacancy'?'Publish this vacancy and lock its requirements?':'Close this vacancy to new applications?'))return;await api('/employer/vacancies/'+pathId(id)+'/'+(action==='open-vacancy'?'open':'close'),'POST');flash('Vacancy updated.');}if(['review','shortlist','reject'].includes(action)){if(action!=='review'&&!confirm((action==='reject'?'Reject':'Shortlist')+' this application?'))return;await api('/recruiter/applications/'+pathId(id)+'/'+action,'POST');flash('Application updated.');}await render();}catch(error){flash(error.message);}finally{target.disabled=false;}}
async function submit(event){const form=event.target.closest('[data-form]');if(!form)return;event.preventDefault();const values=Object.fromEntries(new FormData(form));if(form.dataset.form==='search'){const query=new URLSearchParams();for(const key of ['q','location'])if(values[key].trim())query.set(key,values[key].trim());location.hash='jobs?'+query;return;}const submitButton=form.querySelector('button[type="submit"]');submitButton.disabled=true;try{if(form.dataset.form==='skill')await api('/candidate/skills','POST',{skillName:values.skillName});if(form.dataset.form==='vacancy'){const created=await api('/employer/vacancies','POST',values);location.hash='manage/'+created.id;flash('Draft created. Add your requirements before publishing.');return;}if(form.dataset.form==='requirement')await api('/employer/vacancies/'+pathId(form.dataset.id)+'/requirements','POST',{...values,category:'Skill',requirementType:values.required==='true'?'REQUIRED':'PREFERRED',required:values.required==='true'});if(form.dataset.form==='assign')await api('/employer/vacancies/'+pathId(form.dataset.id)+'/recruiter','POST',{recruiterId:values.recruiterId});flash('Saved successfully.');await render();}catch(error){flash(error.message);}finally{submitButton.disabled=false;}}
content.addEventListener('click',action);content.addEventListener('submit',submit);window.addEventListener('hashchange',render);
document.getElementById('sign-in').addEventListener('click',()=>{location.hash='workspace';if(location.hash==='#workspace')render();});
document.getElementById('sign-out').addEventListener('click',async()=>{try{await window.Clerk.signOut();session=null;location.hash='home';await refreshSession();await render();}catch{flash('Could not sign out. Please try again.');}});
window.addEventListener('load',async()=>{try{authEnabled=(await api('/site-config')).authenticationEnabled;if(authEnabled){if(!window.Clerk)throw new Error('Sign-in could not load. Check your connection and try again.');await window.Clerk.load({ui:{ClerkUI:window.__internal_ClerkUICtor}});await refreshSession();providerSessionId=window.Clerk.session?.id||null;window.Clerk.addListener(({session:current})=>{const next=current?.id||null;if(next!==providerSessionId){providerSessionId=next;refreshSession().then(render).catch(error=>flash(error.message));}});}await render();}catch(error){flash(error.message);await render();}});
})();
`;
